tests.testCrazedAlchemist = function() {
  var p1 = new Player([], new Hunter());
  var p2 = new Player([], new Mage());
  var game = new Hearthstone([p1, p2], 0);
  p1.hand.push(NeutralCards.Sheep.copy());
  p1.hand.push(HunterCards.TimberWolf.copy());
  p1.hand.push(NeutralCards.Shieldbearer.copy());
  p1.hand.push(NeutralCards.CrazedAlchemist.copy());
  p1.hand.push(NeutralCards.CrazedAlchemist.copy());
  p1.hand.push(NeutralCards.CrazedAlchemist.copy());
  p1.currentMana = 9;
  p1.turn.playCard(p1.hand[0], 0);
  p1.turn.playCard(p1.hand[0], 1);
  assert(2, p1.minions[0].getCurrentAttack());
  p1.turn.playCard(p1.hand[0], 2);
  p1.turn.playCard(p1.hand[0], 3, p1.minions[0]);
  assert(2, p1.minions[0].currentHp);
  assert(2, p1.minions[0].getCurrentAttack());
  p1.turn.playCard(p1.hand[0], 4, p1.minions[0]);
  assert(2, p1.minions[0].currentHp);
  assert(3, p1.minions[0].getCurrentAttack());
  p1.turn.playCard(p1.hand[0], 5, p1.minions[2]);
  assert(5, p1.minions.length);
};

tests.testIronforgeRifleman = function() {
  var p1 = new Player([], new Mage());
  var p2 = new Player([], new Mage());
  var game = new Hearthstone([p1, p2], 0);
  p1.hand.push(NeutralCards.IronforgeRifleman.copy());
  p1.hand.push(NeutralCards.IronforgeRifleman.copy());
  p1.hand.push(NeutralCards.IronforgeRifleman.copy());
  p1.currentMana = 9;
  p1.turn.playCard(p1.hand[0], 0, p1.hero);
  assert(28, p1.hero.hp);
  p1.turn.playCard(p1.hand[0], 0, p2.hero);
  assert(29, p2.hero.hp);
  p1.turn.playCard(p1.hand[0], 0, p1.minions[0]);
  assert(1, p1.minions[1].currentHp);
};

tests.testLeperGnome = function() {
  var p1 = new Player([], new Mage());
  var p2 = new Player([], new Mage());
  var game = new Hearthstone([p1, p2], 0);
  p1.hand.push(NeutralCards.LeperGnome.copy());
  p1.hand.push(NeutralCards.LeperGnome.copy());
  p1.currentMana = 4;
  p1.turn.playCard(p1.hand[0], 0);
  p1.turn.playCard(p1.hand[0], 0);
  p1.turn.useHeroPower(p1.minions[0]);
  assert(1, p1.minions.length);
  assert(28, p2.hero.hp);
  p1.turn.endTurn();
  p2.currentMana = 2;
  p2.turn.useHeroPower(p1.minions[0]);
  assert(0, p1.minions.length);
  assert(25, p2.hero.hp);
};

tests.testWildPyromancer = function() {
  var p1 = new Player([], new Mage());
  var p2 = new Player([], new Mage());
  var game = new Hearthstone([p1, p2], 0);
  p1.hand.push(NeutralCards.WildPyromancer.copy());
  p1.currentMana = 2;
  p1.turn.playCard(p1.hand[0], 0);
  assert(1, p1.minions.length);
  assert('Wild Pyromancer', p1.minions[0].name);
  assert(2, p1.minions[0].currentHp);
  p1.turn.endTurn();
  p2.hand.push(MageCards.MirrorImage.copy());
  p2.turn.playCard(p2.hand[1]);
  assert(2, p1.minions[0].currentHp);
  p2.turn.endTurn();
  p1.hand.push(MageCards.WaterElemental.copy());
  p1.hand.push(MageCards.MirrorImage.copy());
  p1.hand.push(MageCards.Fireball.copy());
  p1.currentMana = 9;
  p1.turn.playCard(p1.hand[0], 0);
  assert('Water Elemental', p1.minions[0].name);
  assert(6, p1.minions[0].currentHp);
  assert(2, p1.minions[1].currentHp);
  assert(2, p2.minions.length);
  assert(2, p2.minions[0].currentHp);
  assert(2, p2.minions[1].currentHp);
  assert(29, p2.hero.hp);
  assert(27, p1.hero.hp);
  p1.turn.playCard(p1.hand[0]);
  assert(1, p1.hand.length);
  assert(4, p1.minions.length);
  assert(5, p1.minions[0].currentHp);
  assert(1, p1.minions[1].currentHp);
  assert(1, p1.minions[2].currentHp);
  assert(1, p1.minions[3].currentHp);
  assert(2, p2.minions.length);
  assert(1, p2.minions[0].currentHp);
  assert(1, p2.minions[1].currentHp);
  assert(29, p2.hero.hp);
  assert(27, p1.hero.hp);
  p1.turn.playCard(p1.hand[0], undefined, p1.minions[1]);
  assert(3, p1.minions.length);
  assert(5, p1.minions[0].currentHp);
  assert(1, p1.minions[1].currentHp);
  assert(1, p1.minions[2].currentHp);
  assert(2, p2.minions.length);
  assert(1, p2.minions[0].currentHp);
  assert(1, p2.minions[1].currentHp);
  assert(29, p2.hero.hp);
  assert(27, p1.hero.hp);
};